services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
          ignore:
            - vendor
        - action: rebuild
          path: composer.json
    depends_on:
      - mysql
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`softwear.guru`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    networks:
      - traefik-proxy
      - internal

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    develop:
      watch:
        - action: rebuild
          path: package.json
    ports:
      - 5173:5173
    depends_on:
      - laravel
  mysql:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mysql
      - PMA_port=3306
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  mysql_data:


networks:
  traefik-proxy:
    external: true
  internal:
    driver: bridge
